---
- name: Instalar herramientas Hyper-V y reiniciar
  hosts: all
  become: true
  serial: 1
  tasks:

    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Instalar metapaquetes de herramientas Hyper-V
      apt:
        name:
          - linux-tools-virtual
          - linux-cloud-tools-virtual
        state: present

    - name: Reiniciar la VM y esperar reconexión
      reboot:
        reboot_timeout: 300
        connect_timeout: 20
        test_command: uptime
